Repository terra-money/classic-core, pull requests merged in 2019-11, with the labels that each got.

#264 shortened default oracle voteperiod to 30 seconds.
  x/oracle/internal/types/params.go
Labels: enhancement

#262 Delete non used file
  tools-stamp
Labels: style

#267 [Feature] minor treasury comments update
  x/treasury/abci.go
  x/treasury/genesis.go
  x/treasury/handler.go
  x/treasury/internal/keeper/indicator.go
  x/treasury/internal/keeper/keeper.go
  x/treasury/internal/keeper/params.go
  x/treasury/internal/keeper/policy.go
  x/treasury/internal/keeper/querier.go
  x/treasury/internal/keeper/seigniorage.go
  x/treasury/internal/types/events.go
Labels: enhancement

#269 change treasury keeper to store only indicators for the each epoch
  app/export.go
  client/lcd/swagger-ui/swagger.yaml
  docs/specifications/treasury.md
  tools-stamp
  x/auth/ante.go
  x/auth/client/utils/feeutils.go
  x/auth/internal/types/expected_keeper.go
  x/auth/test_utils.go
  x/treasury/abci.go
  x/treasury/abci_test.go
  x/treasury/alias.go
  x/treasury/client/cli/query.go
  x/treasury/client/rest/query.go
  x/treasury/genesis.go
  x/treasury/genesis_test.go
  x/treasury/handler.go
  x/treasury/internal/keeper/indicator.go
  x/treasury/internal/keeper/indicator_test.go
  x/treasury/internal/keeper/keeper.go
  x/treasury/internal/keeper/keeper_test.go
  x/treasury/internal/keeper/policy.go
  x/treasury/internal/keeper/policy_test.go
  x/treasury/internal/keeper/querier.go
  x/treasury/internal/keeper/querier_test.go
  x/treasury/internal/keeper/seigniorage.go
  x/treasury/internal/keeper/seigniorage_test.go
  x/treasury/internal/keeper/test_utils.go
  x/treasury/internal/types/genesis.go
  x/treasury/internal/types/genesis_test.go
  x/treasury/internal/types/keys.go
  x/treasury/internal/types/querier.go
  x/treasury/proposal_handler_test.go
Labels: enhancement

#273 Remove git caching in circleci jobs
  .circleci/config.yml
Labels: devops

#274 [Bugfix] Fix oracle rest path
  x/oracle/client/rest/query.go
Labels: bug, client

#276 [Bug] Skip oracle slashing for the not passed ballot
  client/lcd/swagger-ui/swagger.yaml
  x/market/internal/types/params.go
  x/oracle/abci.go
  x/oracle/abci_test.go
Labels: bug, enhancement

#283 [Bugfix] Add features to sync swagger doc
  Makefile
  contrib/devtools/Makefile
  contrib/devtools/install-golangci-lint.sh
Labels: bug

#279 [Bug] Align oracle parameters to units of blocks
  x/oracle/abci_test.go
  x/oracle/internal/keeper/reward.go
  x/oracle/internal/keeper/reward_test.go
  x/oracle/internal/types/params.go
  x/oracle/internal/types/params_test.go
  x/oracle/slash_test.go
  x/oracle/slashing.go
  x/oracle/test_utils.go
Labels: bug

#281 [Bug] fix to apply reward spread by multiplication
  x/oracle/abci_test.go
  x/oracle/tally.go
Labels: bug

#290 [Bug] Create new event manager per tx
  x/market/handler.go
  x/oracle/handler.go
Labels: bug

#288 [Feature] oracle MsgDelegateFeedConsent.Deleagtee to Delegate
  x/oracle/client/cli/query.go
  x/oracle/genesis.go
  x/oracle/handler.go
  x/oracle/internal/keeper/keeper.go
  x/oracle/internal/keeper/keeper_test.go
  x/oracle/internal/keeper/querier.go
  x/oracle/internal/keeper/querier_test.go
  x/oracle/internal/types/msgs.go
  x/oracle/internal/types/msgs_test.go
  x/oracle/internal/types/params.go
Labels: enhancement

#268 clog update
  CHANGELOG.md
Labels: WIP

#291 [Bugfix] oracle & market overflow
  x/market/alias.go
  x/market/internal/keeper/querier.go
  x/market/internal/keeper/querier_test.go
  x/market/internal/keeper/swap.go
  x/market/internal/types/errors.go
  x/market/internal/types/msgs.go
  x/market/internal/types/msgs_test.go
  x/oracle/internal/types/errors.go
  x/oracle/internal/types/msgs.go
  x/oracle/internal/types/msgs_test.go
Labels: bug
