Repository terra-money/classic-core, pull requests merged in 2019-06, with the labels that each got.

#150 Feature/oracle spread
  app/app.go
  docs/guide/validators.md
  types/claim.go
  types/claimpool.go
  types/util/epoch.go
  x/bench/bench_test_common.go
  x/bench/treasury_bench_test.go
  x/budget/end_blocker.go
  x/budget/end_blocker_test.go
  x/budget/expected_keepers.go
  x/budget/keeper.go
  x/budget/keeper_keys.go
  x/budget/keeper_test.go
  x/budget/test_common.go
  x/market/errors.go
  x/market/expected_keeper.go
  x/market/handler.go
  x/market/handler_test.go
  x/market/keeper.go
  x/market/keeper_test.go
  x/market/log.go
  x/market/params.go
  x/market/spread.go
  x/market/tags/tags.go
  x/market/test_common.go
  x/mint/keeper.go
  x/mint/keeper_test.go
  x/oracle/end_blocker.go
  x/oracle/end_blocker_test.go
  x/oracle/expected_keepers.go
  x/oracle/keeper.go
  x/oracle/keeper_keys.go
  x/oracle/keeper_test.go
  x/oracle/params.go
  x/oracle/tags/tags.go
  x/oracle/test_common.go
  x/pay/handler_test.go
  x/treasury/end_blocker.go
  x/treasury/end_blocker_test.go
  x/treasury/expected_keepers.go
  x/treasury/genesis.go
  x/treasury/indicator.go
  x/treasury/indicator_test.go
  x/treasury/keeper.go
  x/treasury/keeper_test.go
  x/treasury/params.go
  x/treasury/querier.go
  x/treasury/querier_test.go
  x/treasury/test_common.go
Labels: enhancement, must, test

#157 staking validators querier update
  x/budget/handler.go
  x/staking/client/rest/query.go
Labels: bug, client

#170 Documentation update for Columbus-2
  CHANGELOG.md
  README.md
  client/lcd/swagger-ui/swagger.yaml
  docs/features/overview/README.md
  docs/features/overview/validator-faq.md
  docs/features/stability.md
  docs/guide/installation.md
  docs/guide/join-network.md
  docs/guide/terracli.md
  docs/guide/users.md
  docs/spec/oracle.md
  x/market/client/cli/query.go
  x/market/client/cli/tx.go
  x/market/client/module_client.go
  x/oracle/client/cli/query.go
  x/oracle/client/cli/tx.go
  x/pay/client/cli/sendtx.go
  x/treasury/client/cli/query.go
Labels: docs, style

#176 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#177 Create pull_request_template.md
  .github/pull_request_template.md
Labels: enhancement

#178 apply bip44 luna coin type
  cmd/terracli/main.go
  cmd/terrad/main.go
  go.mod
  go.sum
  testutil/cmd.go
Labels: client, daemon

#182 update cosmos-sdk version to support ledger hrp customization
  go.mod
  go.sum
Labels: bug

#183 Feature/ Lazy Vesting Schedule
  CHANGELOG.md
  app/app.go
  app/genesis.go
  client/lcd/swagger-ui/swagger.yaml
  types/codec.go
  types/lazy_graded_account.go
  types/lazy_graded_account_test.go
  update/end_blocker.go
  update/plan/test_common.go
  update/plan/update_230000.go
  update/plan/update_230000_test.go
Labels: daemon, enhancement

#187 Bugfix/fix-time-zone
  CHANGELOG.md
  types/graded_account_test.go
  types/lazy_graded_account_test.go
  update/plan/update_230000.go
  update/plan/update_230000_test.go
Labels: bug, daemon, must, test

#188 v0.2.3
  CHANGELOG.md
  types/graded_account_test.go
  types/lazy_graded_account_test.go
  update/plan/update_230000.go
  update/plan/update_230000_test.go
Labels: urgent
