Repository terra-money/classic-core, pull requests merged in 2019-07, with the labels that each got.

#203 Bugfix/repository language
  .gitattributes
Labels: bug

#193 Feature/recover-old-hd-path
  CHANGELOG.md
  Makefile
  client/keys/.gitignore
  client/keys/add.go
  client/keys/add_ledger_test.go
  client/keys/add_test.go
  client/keys/codec.go
  client/keys/codec_test.go
  client/keys/delete.go
  client/keys/delete_test.go
  client/keys/errors.go
  client/keys/list.go
  client/keys/list_test.go
  client/keys/mnemonic.go
  client/keys/mnemonic_test.go
  client/keys/root.go
  client/keys/root_test.go
  client/keys/show.go
  client/keys/show_test.go
  client/keys/types.go
  client/keys/update.go
  client/keys/update_test.go
  client/keys/utils.go
  cmd/terracli/main.go
  cmd/terrad/main.go
  go.mod
  types/util/hdpath.go
Labels: client, enhancement

#211 Change cosmos-sdk's mock ledger to accept custom coin type from config
  Makefile
  client/keys/add_ledger_test.go
  go.mod
  go.sum
Labels: bug

#196 Bugfix/peek epoch seigniorage
  CHANGELOG.md
  x/mint/keeper.go
  x/mint/keeper_test.go
  x/treasury/indicator_test.go
  x/treasury/querier_test.go
Labels: bug, must

#198 Bugfix/treasury update target epoch
  x/treasury/policy.go
Labels: bug, must

#217 Updated CHANGELOG
  .github/pull_request_template.md
  CHANGELOG.md
Labels: docs
