Repository terra-money/classic-core, pull requests merged in 2020-11, with the labels that each got.

#419 [Bugfix] allow language specific decimal precision error in vesting schedule validation
  x/auth/vesting/types/schedule.go
Labels: bug

#429 Revert "[Bugfix] Make all error code bigger than 1"
  x/market/internal/types/errors.go
  x/msgauth/internal/types/errors.go
  x/oracle/internal/types/errors.go
  x/treasury/alias.go
  x/treasury/internal/types/errors.go
  x/wasm/internal/types/errors.go
Labels: bug

#426 [Feature] CosmWasm cache update
  Dockerfile
  go.mod
  go.sum
Labels: wasm

#427 [Bugfix] Register wasm queriers after staking keeper initialization
  app/app.go
Labels: bug, must

#432 [Bugfix] Prevent panic when external contract query executed
  x/wasm/internal/keeper/querier.go
  x/wasm/internal/keeper/recursive_test.go
Labels: bug, enhancement

#433 [Upgrade] Softfork for WASM Updates
  app/app.go
  types/alias.go
  types/util/softfork.go
  x/market/internal/keeper/swap.go
  x/market/internal/types/errors.go
  x/oracle/abci_test.go
  x/oracle/alias.go
  x/oracle/handler.go
  x/oracle/internal/keeper/keeper.go
  x/oracle/internal/keeper/querier.go
  x/oracle/internal/types/errors.go
  x/oracle/internal/types/msgs.go
  x/oracle/test_utils.go
  x/treasury/alias.go
  x/treasury/internal/types/errors.go
  x/wasm/abci.go
  x/wasm/internal/keeper/contract.go
  x/wasm/internal/types/errors.go
  x/wasm/internal/types/query_binding.go
  x/wasm/module.go
Labels: bug, daemon, enhancement, must
