Repository terra-money/classic-core, pull requests merged in 2020-08, with the labels that each got.

#377 [Bugfix] Convert Custom JSON Marshaling Codec to Amino Codec
  x/auth/simulation/genesis.go
  x/auth/vesting/types/vesting_account.go
  x/auth/vesting/types/vesting_account_test.go
Labels: WIP, bug

#378 [Feature] Bump CosmWasm to v0.10
  go.mod
  go.sum
  x/wasm/alias.go
  x/wasm/genesis.go
  x/wasm/internal/keeper/api.go
  x/wasm/internal/keeper/contract.go
  x/wasm/internal/keeper/contract_test.go
  x/wasm/internal/keeper/custom_test.go
  x/wasm/internal/keeper/keeper_test.go
  x/wasm/internal/keeper/params.go
  x/wasm/internal/keeper/querier.go
  x/wasm/internal/keeper/recursive_test.go
  x/wasm/internal/keeper/testdata/burner.wasm
  x/wasm/internal/keeper/testdata/contract.wasm
  x/wasm/internal/keeper/testdata/contract.wasm.gzip
  x/wasm/internal/keeper/testdata/maker.wasm
  x/wasm/internal/keeper/testdata/mask.wasm
  x/wasm/internal/keeper/testdata/staking.wasm
  x/wasm/internal/keeper/wasm_interface.go
  x/wasm/internal/types/contract.go
  x/wasm/internal/types/genesis_test.go
  x/wasm/internal/types/params.go
  x/wasm/internal/types/params_test.go
  x/wasm/internal/types/query_binding.go
  x/wasm/simulation/decoder_test.go
  x/wasm/simulation/genesis.go
  x/wasm/simulation/params.go
  x/wasm/simulation/test_contract.go
Labels: enhancement

#383 [Feature] Bump SDK to v0.39.1
  go.mod
  go.sum
Labels: daemon

#382 [Feature] Use custom go-cosmwasm for signal propagation
  go.mod
  go.sum
Labels: enhancement

#381 [Oracle] Exchange Rate and Ballot Rewards logic using reference terra
  x/oracle/abci.go
  x/oracle/abci_test.go
  x/oracle/internal/keeper/keeper.go
  x/oracle/internal/keeper/test_utils.go
  x/oracle/tally.go
  x/oracle/test_utils.go
Labels: enhancement

#385 [Feature] Clean oracle module
  x/oracle/abci.go
  x/oracle/internal/keeper/keeper.go
  x/oracle/internal/types/ballot.go
  x/oracle/internal/types/ballot_test.go
  x/oracle/tally.go
Labels: style

#384 [Feature] Mint Module
  app/app.go
  app/sim_test.go
  cli_test/cli_test.go
  cli_test/test_helpers.go
  x/mint/cosmos_alias.go
  x/mint/module.go
Labels: daemon, enhancement

#387 [Feature] swagger update for mint module
  .github/pull_request_template.md
  client/lcd/swagger-ui/swagger.yaml
Labels: docs
