Repository terra-money/classic-core, pull requests merged in 2020-07, with the labels that each got.

#357 [Feature] Bump cosmwasm to v0.9
  app/app.go
  client/lcd/swagger-ui/swagger.yaml
  go.mod
  go.sum
  x/auth/ante/tax_test.go
  x/wasm/alias.go
  x/wasm/client/cli/tx.go
  x/wasm/client/rest/tx.go
  x/wasm/genesis.go
  x/wasm/genesis_test.go
  x/wasm/handler.go
  x/wasm/handler_test.go
  x/wasm/internal/keeper/contract.go
  x/wasm/internal/keeper/contract_test.go
  x/wasm/internal/keeper/custom_test.go
  x/wasm/internal/keeper/keeper_test.go
  x/wasm/internal/keeper/mask_test.go
  x/wasm/internal/keeper/querier_test.go
  x/wasm/internal/keeper/staking_test.go
  x/wasm/internal/keeper/test_utils.go
  x/wasm/internal/keeper/testdata/burner.wasm
  x/wasm/internal/keeper/testdata/contract.wasm
  x/wasm/internal/keeper/testdata/contract.wasm.gzip
  x/wasm/internal/keeper/testdata/maker.wasm
  x/wasm/internal/keeper/testdata/mask.wasm
  x/wasm/internal/keeper/testdata/staking.wasm
  x/wasm/internal/keeper/wasm_interface.go
  x/wasm/internal/types/codec.go
  x/wasm/internal/types/connector.go
  x/wasm/internal/types/contract.go
  x/wasm/internal/types/errors.go
  x/wasm/internal/types/events.go
  x/wasm/internal/types/msg.go
  x/wasm/internal/types/msg_test.go
  x/wasm/internal/types/query_binding.go
  x/wasm/module.go
  x/wasm/simulation/decoder_test.go
  x/wasm/simulation/operations.go
  x/wasm/simulation/test_contract.go
  x/wasm/test_utils.go
  x/wasm/testdata/escrow.wasm
  x/wasm/testdata/escrow_0.7.wasm
Labels: daemon, enhancement, must

#349 [Feature] support old-hd-path flag
  cmd/terracli/main.go
Labels: client, enhancement

#352 [Feature] msg authorization module
  app/app.go
  app/app_test.go
  app/sim_test.go
  client/lcd/swagger-ui/swagger.yaml
  x/auth/ante/tax.go
  x/auth/ante/tax_test.go
  x/auth/client/utils/feeutils.go
  x/bank/internal/types/codec.go
  x/market/internal/types/codec.go
  x/msgauth/abci.go
  x/msgauth/abci_test.go
  x/msgauth/alias.go
  x/msgauth/client/cli/query.go
  x/msgauth/client/cli/tx.go
  x/msgauth/client/rest/query.go
  x/msgauth/client/rest/rest.go
  x/msgauth/client/rest/tx.go
  x/msgauth/exported/alias.go
  x/msgauth/genesis.go
  x/msgauth/genesis_test.go
  x/msgauth/handler.go
  x/msgauth/handler_test.go
  x/msgauth/internal/keeper/keeper.go
  x/msgauth/internal/keeper/keeper_test.go
  x/msgauth/internal/keeper/querier.go
  x/msgauth/internal/keeper/querier_test.go
  x/msgauth/internal/keeper/test_common.go
  x/msgauth/internal/types/authorizations.go
  x/msgauth/internal/types/codec.go
  x/msgauth/internal/types/errors.go
  x/msgauth/internal/types/events.go
  x/msgauth/internal/types/generic_authorization.go
  x/msgauth/internal/types/genesis.go
  x/msgauth/internal/types/genesis_test.go
  x/msgauth/internal/types/keys.go
  x/msgauth/internal/types/msgs.go
  x/msgauth/internal/types/msgs_test.go
  x/msgauth/internal/types/querier.go
  x/msgauth/internal/types/send_authorization.go
  x/msgauth/module.go
  x/msgauth/simulation/decoder.go
  x/msgauth/simulation/decoder_test.go
  x/msgauth/simulation/operations.go
  x/wasm/module.go
Labels: daemon, enhancement

#364 [Bugfix] WASM module codec naming
  x/wasm/internal/types/codec.go
  x/wasm/internal/types/msg.go
Labels: bug, style

#374 Bump CosmWasm and SDK
  cmd/terrad/main.go
  cmd/terrad/replay.go
  go.mod
  go.sum
  x/wasm/internal/keeper/contract_test.go
Labels: enhancement

#376 [Bugfix] Allow insufficient fee error for msgauth simulation
  x/msgauth/simulation/operations.go
Labels: bug

#379 fix: stringify yes and no map keys
  client/lcd/swagger-ui/swagger.yaml
Labels: bug, client
