Repository terra-money/classic-core, pull requests merged in 2020-09, with the labels that each got.

#388 [Feature] Bump cosmwasm to v0.10.1
  go.mod
  go.sum
Labels: enhancement

#396 [Feature] WASM store path customization
  cmd/terrad/main.go
  x/wasm/config/config.go
  x/wasm/internal/keeper/keeper.go
Labels: enhancement

#398 [Bugfix] Wasm instantiate process
  x/wasm/internal/keeper/contract.go
  x/wasm/internal/keeper/contract_test.go
Labels: bug, must

#397 Update swagger on docker image build
  Dockerfile
Labels: devops

#402 [Audit] apply Certik audit report
  x/market/internal/types/msgs.go
  x/msgauth/client/rest/rest.go
  x/msgauth/client/rest/tx.go
  x/msgauth/internal/keeper/keeper.go
  x/wasm/client/utils/utils.go
  x/wasm/internal/keeper/api.go
Labels: enhancement

#405 [Feature] WASM oracle querier
  app/app.go
  x/oracle/wasm/interface.go
  x/oracle/wasm/interface_test.go
  x/treasury/wasm/interface_test.go
  x/wasm/alias.go
  x/wasm/internal/keeper/custom_test.go
  x/wasm/internal/keeper/test_utils.go
  x/wasm/internal/keeper/testdata/bindings_tester.wasm
  x/wasm/internal/types/query_binding.go
Labels: enhancement, wasm

#371 CHANGELOG update
  CHANGELOG.md
Labels: docs

#407 [Feature] Allow gov msg to be grantable
  app/app.go
  x/gov/internal/types/codec.go
  x/msgauth/client/cli/query.go
Labels: enhancement
