Repository terra-money/classic-core, pull requests merged in 2020-06, with the labels that each got.

#340 [Bugfix] Oracle Slashing
  x/oracle/abci.go
  x/oracle/internal/keeper/keeper.go
  x/oracle/internal/keeper/keeper_test.go
  x/oracle/slash_test.go
  x/oracle/slashing.go
Labels: bug, daemon

#343 [Feature] Burn Address
  app/app.go
  x/bank/abci.go
  x/bank/abci_test.go
  x/bank/alias.go
  x/bank/internal/types/expected_keepers.go
  x/bank/internal/types/keys.go
  x/bank/module.go
Labels: enhancement

#351 Update broken url link in swagger
  client/lcd/swagger-ui/swagger.yaml
Labels: docs

#355 [Feature] add swap receiver attribute tag
  x/market/handler.go
  x/market/internal/types/events.go
Labels: enhancement

#353 [Feature] market client interface tax calculation
  client/lcd/swagger-ui/swagger.yaml
  x/auth/ante/tax.go
  x/auth/client/utils/feeutils.go
  x/market/client/cli/tx.go
  x/market/client/rest/tx.go
  x/market/exported/alias.go
  x/treasury/exported/alias.go
Labels: client

#350 [Feature] WASM add params querier interface & align client interface
  client/lcd/swagger-ui/swagger.yaml
  x/wasm/client/cli/query.go
  x/wasm/client/cli/tx.go
  x/wasm/client/rest/query.go
  x/wasm/client/rest/tx.go
  x/wasm/internal/keeper/querier.go
  x/wasm/internal/keeper/querier_test.go
  x/wasm/internal/types/querier.go
Labels: client
