Repository terra-money/classic-core, pull requests merged in 2021-11, with the labels that each got.

#601 [Feature] remove readvm-pool feature
  CHANGELOG.md
  go.mod
  go.sum
  x/wasm/config/config.go
  x/wasm/keeper/contract.go
  x/wasm/keeper/keeper.go
  x/wasm/keeper/legacy_querier.go
  x/wasm/keeper/pool.go
  x/wasm/keeper/querier.go
  x/wasm/keeper/recursive_test.go
  x/wasm/types/keys.go
  x/wasm/types/wasmer_engine.go
Labels: bug, enhancement, wasm

#603 [Bugfix] Bump wasmvm to v0.16.2
  CHANGELOG.md
  go.mod
  go.sum
Labels: bug, wasm

#594 [Bump] SDK versions to cosmos-sdk@v0.44.3 and tendermint@v0.34.14
  CHANGELOG.md
  cmd/terrad/root.go
  go.mod
  go.sum
Labels: enhancement

#610 Update Docker images to use the `--db_dir` flag.
  docker/Dockerfile
  docker/README.md
  docker/build_all.sh
  docker/entrypoint.sh
Labels: devops
